resource_group_name = "myResourceGroup"
location            = "East US"
vnet_name           = "myVNet"
subnet_name         = "mySubnet"
public_ip_name      = "myPublicIP"
nic_name            = "myNIC"
vm_name             = "myVM"
admin_username      = "azureuser"
admin_password      = "Password1234!"
subscription_id     = ARM_SUBSCRIPTION_ID
client_id           = ARM_CLIENT_ID
client_secret       = ARM_CLIENT_SECRET
tenant_id           = ARM_TENANT_ID
